### ISSUE TITLE
OBS builds are failing for the runtime

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#3321]
**Describe the bug**
I tried to use OBS RPMs for the runtime and I expected them to be building instead they are broken.

**GEOPM version**
Tip of dev

**Expected behavior**
Expected successful builds and the availability of the latest runtime RPMs here:
https://build.opensuse.org/package/show/home:geopm/geopm-runtime

**Actual behavior**
Build logs show:
```
[   26s] In file included from src/Admin.cpp:18:0:
[   26s] /usr/include/geopm/MSRIOGroup.hpp:20:10: fatal error: Cpuid.hpp: No such file or directory
[   26s]  #include "Cpuid.hpp"
[   26s]           ^~~~~~~~~~~
[   26s] compilation terminated.
[   26s] make[1]: *** [Makefile:5130: src/libgeopm_la-Admin.lo] Error 1
```

**Additional context**
Introduced in #3297.
