### PR TITLE
Address ABI compatability issues between dev and 3.0.1.

### LINKED ISSUE #3361: 3.0.1 ABI compatibility broken on dev
**Describe the bug**
I tried to use the runtime (geopmctl) built from the tip of dev linked against libgeopmd2.so from the 3.0.1 tag, and a 3.0.1 installed version of the service and I expected it to work instead an error is returned.

**GEOPM version**
Installed service @ 3.0.1
Runtime from 9550e179b

**Expected behavior**
No errors.

**Actual behavior**
```
$ geopmctl --help
geopmctl: symbol lookup error: /home/bgeltz/build/geopm/lib/libgeopm.so.2: undefined symbol: _ZN5geopm4hashERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Additional context**
The ABI breaking change that causes the above error was introduced in PR #3296.

There is also an issue if you attempt to build the runtime from 3.0.1 against libgeopmd from dev.  In that case a complile time error is encountered:
```
src/Admin.cpp:28:29: error: no member named 'cpuid' in 'geopm::MSRIOGroup'
```
Introduced in PR #3297.

Additional PRs for context: 
- #3296
- #3320

### PR DESCRIPTION
**Pull request by bgeltz**
- Fixes #3361.

### CODE REVIEW

**Review by bgeltz — COMMENTED** [review]
Make std::hex, etc. changes in the top of the stringstreams in the ReporterTest.

Remove depreciation notice in the crc32 hash API, and remove the geopm_hash API since it's effecively a dupe now.

Move the DeprecationWarning implementaiton into Helper.cpp.

**Review by cmcantalupo — APPROVED** [review]
